name: first workflow


on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: megz


    steps:
      - name: print a welcome message
        run: echo "welcome ya prins ${{ vars.TEST }}"
