name: first workflow


on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    environment: megz


    steps:
      - name: print a welcome message
        run: echo "welcome ya prins ${{ vars.TEST }} ${{ vars.DAD }}"
      - name: password test
        run: echo "Password is ${{ secrets.PASS }}"
      - run: echo "APP_ENV=staging" >> "$GITHUB_ENV"
      - run: echo "$APP_ENV"
